language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
env:
  - CI=true
script:
  - npm run build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github-token # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
